# Generated by Django 4.2.6 on 2023-11-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='content',
            field=models.TextField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='count_like',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='estimation',
            field=models.IntegerField(null=True, verbose_name='Оценка'),
        ),
    ]
